name: "Feature workflow"

on:
  push:
    branches: 
      - feature/*
  
jobs:
  demo_job:
    steps:
      - name: Say hello
        run: echo "Hello World!"
    steps:
      - name: The time is:
        run: date
    steps:
      - name: Contents of the current file are:
        run: ls -l