name: Feature workflow

on:
  push:
    branches: 
      - feature/*
  
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: List repo files
        run: ls
        
      - name: List project files
        run: cd src | ls
        
      - name: Run units tests
        run: echo "Running tests..."