name: Feature workflow

on:
  push:
    branches: 
      - feature/*
  
jobs:
  demo-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo 'Hello World!
        
      - name: The time is:
        run: date
        
      - name: Contents of the current file are:
        run: ls -l